---
     # deployment setup    
    nsVersion: ns-allinone-3.35
    nsCodeFolder: ns-3.35
    extension: .tar.bz2
    deployFolder: /home/dockemu/src/dockemu
    optimized: false

      # experiment configuration
      # base container name should not contain non-alfanumeric chars 
      # max 8 chars 
    baseContainerName: jacktrip
    experimentName: jacktrip-experiment
    serverCommand: jacktrip -S -z -p4 --udprt -q auto -I 1 -G /var/log/dockemu/jacktrip-io.log > /var/log/dockemu/jacktrip-server.log &
#    serverCommand: jacktrip -S -z -p4 --udprt -q auto > /var/log/dockemu/jacktrip-server.log &
    serverStopCommand: killall jacktrip
    clientCommand: jacktrip -C 10.12.0.240 -z --udprt -q auto > /var/log/dockemu/jacktrip-client.log &
    clientStopCommand: killall jacktrip
    logsDirectory: /var/dockemu/logs/
    tracefilePath: "{{ deployFolder }}/{{ experimentName }}/traces"
    numberOfClientNodes: 20
    numberOfServerNodes: 1
    serverNode: True
    emulationTime: 200
    experimentTime: 160
    ns3NetworkScript: tap-csma-virtual-machine-client-server
    #ns3NetworkScript: tap-wifi-virtual-machine-client-server
    tracesEnabled: false
    nodeSpeed: 5
    nodePause: 1
    ns3NetworkParameters: --ns3::CsmaChannel::DataRate=100000000 
 
      # emulation parameters  
    startns3: False
    ns3Jobs: 12
